### PR TITLE
Support Keycloak 4

### PR DESCRIPTION
**Pull request by treydock**
Was necessary to add `template.ftl` in order to add the logo.

### CODE REVIEW

**Comment by treydock** [comment]
Differences from previous appearance:

* Form is now centered
* Login button is now width of main content body
* Main content body is a bit wider

**Comment by treydock** [comment]
screen shot 2018-08-08 at 10 14 44 am

screen shot 2018-08-08 at 10 15 02 am

**Comment by ericfranz** [comment]
I'm okay with this. Of course it would be nice if we could get by without the custom ftl files. There may be an alternative solution for adding the logo, without requiring the `template.ftl` but that could be explored in a separate issue.

See https://www.keycloak.org/docs/latest/release_notes/index.html#themes-and-theme-resources

> It is now possible to hot-deploy themes to Keycloak through a regular provider deployment.

* may change the way we deploy the theme using puppet or the directions for setting up Keycloak with a custom theme

> We have also added support to override the theme for specific clients. If that is not adequate for your needs, then there is also a new Theme Selector SPI that allows you to implement custom logic to select the theme.

* could provide an alternative solution for customizing things like the logo for AweSim and OnDemand

**Comment by treydock** [comment]
I think the new mechanisms are through Java SPIs but that's a guess based on what I've seen in the web portal.  There is no way I could find to specify a theme per client so I think that logic would have to be implemented in the custom theme that is using Java code.

**Pull request merged**
